############################################################################
#
#  Secrets (sops + age)
#
############################################################################

# Derive this machine's age private key from its ssh ed25519 key, install
# at ~/.config/sops/age/keys.txt. Run once per machine. The corresponding
# public key (age1...) must already be a recipient in .sops.yaml.
[group('secrets')]
sops-bootstrap:
    #!/usr/bin/env bash
    set -euo pipefail
    
    config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
    keys_file="$config_dir/sops/age/keys.txt"
    
    if [[ -f $keys_file ]]; then
        echo "$keys_file already exists; skipping."
        exit 0
    fi
    
    mkdir -p "$(dirname "$keys_file")"
    ssh-to-age -private-key -i ~/.ssh/id_ed25519 > "$keys_file"
    chmod 600 "$keys_file"
    echo "wrote $keys_file"
    echo "this machine's age recipient (must be in .sops.yaml):"
    ssh-to-age -i ~/.ssh/id_ed25519.pub


# Regenerate .sops.yaml from keys/*.pub, then re-encrypt every
# secrets/*.yaml. Run after adding or removing a .pub file.
[group('secrets')]
sops-rekey:
    #!/usr/bin/env bash
    set -euo pipefail
    shopt -s nullglob
    user_pubs=(keys/aiz_*.pub)
    host_pubs=(keys/root_*.pub)
    {
        cat <<'EOF'
    # Auto-generated by `just sops-rekey` from keys/*.pub.
    # Every recipient can decrypt every secret. To add or remove a
    # machine, add or remove its .pub file and re-run `just sops-rekey`.
    keys:
      # === user keys (aiz@<host>) ===
    EOF
        for f in "${user_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#aiz_}
            age=$(ssh-to-age -i "$f")
            printf '  - &user_aiz_%s %s\n' "$host" "$age"
        done
        echo "  # === host keys (root@<host>) ==="
        for f in "${host_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#root_}
            age=$(ssh-to-age -i "$f")
            printf '  - &host_%s %s\n' "$host" "$age"
        done
        cat <<'EOF'

    creation_rules:
      - path_regex: ^secrets/.*\.ya?ml$
        key_groups:
          - age:
    EOF
        for f in "${user_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#aiz_}
            printf '          - *user_aiz_%s\n' "$host"
        done
        for f in "${host_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#root_}
            printf '          - *host_%s\n' "$host"
        done
    } > .sops.yaml
    echo "regenerated .sops.yaml"
    shopt -s globstar
    for f in secrets/**/*.yaml secrets/*.yaml; do
        if [[ "$(sops filestatus "$f")" == *'"encrypted":true'* ]]; then
            echo "rekeying $f"
            sops updatekeys -y "$f"
        fi
    done

# Edit a sops-encrypted secrets file. Usage: just sops-edit tailscale.yaml
[group('secrets')]
sops-edit FILE:
    sops secrets/{{FILE}}
