# profile to trim the video

only_active_tracks=yes
preserve_filters=no
append_filter=
codec=-c:v libx264 -crf 18 -preset fast -c:a aac -b:a 320k -movflags +faststart
output_format=$t_$s-$e_$n.mp4
output_directory=
detached=yes
ffmpeg_command=ffmpeg
print=yes
