{
  config,
  lib,
  pkgs,
  ...
}: {
  options.myNixOS.programs.podman = {
    enable = lib.mkEnableOption "enable podman";
  };

  config = lib.mkIf config.myNixOS.programs.podman.enable {
    environment.systemPackages = [pkgs.podman-compose];

    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces = let
      matchAll =
        if !config.networking.nftables.enable
        then "podman+"
        else "podman*";
    in {
      "${matchAll}".allowedUDPPorts = [53];
    };

    virtualisation.oci-containers.backend = "podman";

    # Services
    # hmm maybe these should be moved to a separate module

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = ["multi-user.target"];
    };
  };
}
