# profile to slice the current video without reencoding it
# will snap to keyframes

only_active_tracks=yes
preserve_filters=no
append_filter=
codec=-c copy
output_format=$t_$s-$e_$n.$x
output_directory=
detached=yes
ffmpeg_command=ffmpeg
print=yes
